### ISSUE TITLE
Not working: Error Code 1 Traceback

### ISSUE THREAD

**Issue by politicus** [cs1707/tldr-alfred#15]
Installed the latest version of the workflow. Got this error:

```
[01:07:48.165] Web Development tldr[Script Filter] Queuing argument 'mv'
[01:07:50.673] Web Development tldr[Script Filter] Queuing argument 'm'
[01:07:50.830] Web Development tldr[Script Filter] Queuing argument ''
[01:07:51.304] Web Development tldr[Script Filter] Script with argv '(null)' finished
[01:07:51.309] ERROR: Web Development tldr[Script Filter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "tldr.py", line 46, in query
    rowList = parse_man_page(command)
  File "tldr.py", line 111, in parse_man_page
    page_path = find_page_location(command)
  File "tldr.py", line 63, in find_page_location
    encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/Users/Username/Library/Application Support/Alfred/Workflow Data/com.chedanji.tldr/tldr/pages/index.json'
[01:07:51.711] Web Development tldr[Script Filter] Script with argv '(null)' finished
[01:07:51.719] Web Development tldr[Script Filter] <?xml version="1.0" ?><items><item arg="Please input" autocomplete="" uid="1" valid="no"><title>Please input</title><subtitle/><icon>icon.png</icon></item></items>
```

```
$ which git
/usr/local/bin/git
$ where git 
/usr/local/bin/git
/usr/bin/git
```

No problem using tldr in zsh/iTerm2

**Comment by skibitsky** [comment]
Hello @cs1707,

I have a similar issue in Alfred 4.0.6

```
[10:40:01.322] tldr[Script Filter] Queuing argument ''
[10:40:01.534] tldr[Script Filter] Script with argv '(null)' finished
[10:40:01.538] tldr[Script Filter] <?xml version="1.0" ?><items><item arg="Please input" autocomplete="" uid="1" valid="no"><title>Please input</title><subtitle/><icon>icon.png</icon></item></items>
[10:40:02.488] tldr[Script Filter] Queuing argument 'h'
[10:40:02.675] tldr[Script Filter] Script with argv '(null)' finished
[10:40:02.679] ERROR: tldr[Script Filter] Code 1: Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "tldr.py", line 46, in query
    rowList = parse_man_page(command)
  File "tldr.py", line 111, in parse_man_page
    page_path = find_page_location(command)
  File "tldr.py", line 63, in find_page_location
    encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/Users/Username/Library/Application Support/Alfred/Workflow Data/com.chedanji.tldr/tldr/pages/index.json'
```
